### ISSUE TITLE
[GKE] cluster is ready

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes-sigs/kubetest2#114]
How do I ensure that the cluster is up and running properly?

**Comment by amwat** [comment]
`gcloud` already does a cluster readiness check before exiting so if kubetest2 `Up()` succeeds that should be a good enough indication that the cluster is up?

**Comment by chrislovecnm** [comment]
Well the gcloud readiness check ain’t working fully 😂

No I am now checking that certain pods in kube-system are ready and then the test works.

I mentioned to the folks over at kind that we might want to have a cluster up command. What are your thoughts on adding a list of labels that need to be up and running, then the  runners can check that.

**Comment by chrislovecnm** [comment]
We just started running this binary before starting our tests and it has helped a lot. https://github.com/cockroachdb/cockroach-operator/blob/master/hack/k8s/verify_k8s_running.go 

What do you think if incorporating something like this into kubetest2?

**Comment by amwat** [comment]
similar dependency concerns as https://github.com/kubernetes-sigs/kind/issues/2126#issuecomment-802965562 :)
but yes, definitely seems like a useful thing to have. 

But I'd say them living closer to the tests is WAI?
there are varying degrees of "readiness" (that different tests rely on differently) and ideally the kubetest2 deployer itself should have the minimum of them (which I'm willing to trust gcloud on, as it being the actual cluster provisioner )

which is why even our own (outdated, carried over from kubetest1) notion of `IsUp()` is unused for GKE.
https://github.com/kubernetes-sigs/kubetest2/blob/4dca5cd819e1257cba9ebb806e900e052aa20b66/kubetest2-gke/deployer/up.go#L133-L155

**Comment by chrislovecnm** [comment]
I would say that we need to document that the deployers do not do any health checks of the cluster because we do not want to vendor code such as go-client.  I really don't think there are varying degrees of readiness in my opinion.  If something is not running in kube-system the cluster should not run tests IMO, but maybe that is just me.  I would recommend that we document what we test or don't test that the system is up and running.

**Comment by amwat** [comment]
> because we do not want to vendor code such as go-client

That's not the main reason of why I'm hesitant to add "health checks", that's just why we we'd want to avoid using that specific library directly :) 

> I would say that we need to document that the deployers do not do any health checks of the cluster

That's not true in general, we can do it for say kind with `--wait`. For GKE specifically, yes we don't do any health checks of our own, but `gcloud` does (and if it had a `--wait` that would be something we could do as part of the deployer). Ideally, I'd prefer leaving it up to the provisioner to report when/if the cluster is ready wherever possible.

We only really have our own checks for GCE testing because `cluster/kube-up.sh` is not really a "real" provider and very very legacy, and that check is also very minimal, we only check if nodes are created. https://github.com/kubernetes-sigs/kubetest2/blob/4dca5cd819e1257cba9ebb806e900e052aa20b66/kubetest2-gce/deployer/up.go#L28-L57

>  If something is not running in kube-system the cluster should not run tests IMO

That's not true, e.g. kubectl tests will run just fine (i.e. we can interact with the cluster) as soon as the apiserver is up.
In your specific example (guessing based on https://github.com/kubernetes-sigs/kubetest2/issues/113#issue-833811067) it looks like the tests rely specifically on `metrics-server` being up? in which case I would say the tests needing to do a health check before running against that specific component is WAI.

Also, if that component actually doesn't end up becoming healthy, I would prefer only those tests to fail and others to continue running than just give up running all tests at the deployer level?

**Comment by chrislovecnm** [comment]
`gcloud` is not waiting for all of the services in the kube-system namespece to fully start.  

> That's not true, e.g. kubectl tests will run just fine (i.e. we can interact with the cluster) as soon as the apiserver is up.

Yes but some tests won't pass and we have gotten much better testing results when waiting for the cluster to actually start fully.  Just because the APIServer is running it does not mean that you can run more complex components such as operators. So I content that we document that kubetest is dependant on the checks or lack of checks that the provider has.

**Comment by BenTheElder** [comment]
FWIW in kubernetes the e2e tests do some waiting for readiness rather than depending on anything else, I'm not sure this model is terrible, depending on the tests you may need a varying level of readiness. (some test might need 100% of components on all nodes up and healthy + ready, other tests might be able to start as soon as the API server is up and ready)
