### ISSUE TITLE
kubetest2-openshift - proposed new feature

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes-sigs/kubetest2#128]
Hi all

I am working with Coachroach Labs and their operator, and we need to spin up an open shift cluster for e2e testing.  We are using kubetest2 for both kind and gke currently and it is working great!

Is anyone opposed to having a kubetest2 deployer that wraps the OpenShift installer binary?  I will not vendor any OpenShift specific dependencies.

**Comment by chrislovecnm** [comment]
@amwat thoughts?

**Comment by amwat** [comment]
I don't have any specific objections against it (especially since we clarified re: dependencies.)

Although some things to consider, having it in-tree means it would be coupled with the release lifecycle of this repo (eventually), and would expect at the very least to have community CI running against it.

Note that kubetest2 supports out of tree deployers, have you considered that?
most other providers opted to go that route ^

kops: https://github.com/kubernetes/kops/tree/9dc910bdac92468793b4e4eff9b75524044291bd/tests/e2e/kubetest2-kops
eks: https://github.com/aws/aws-k8s-tester
cluster-api: https://github.com/kubernetes-sigs/kubetest2/issues/48

**Comment by chrislovecnm** [comment]
I think out of tree is a great idea. Where is the interface defined?

**Comment by amwat** [comment]
types are defined here: https://github.com/kubernetes-sigs/kubetest2/blob/master/pkg/types/types.go#L70-L82

Although, the actual contract with kubetest2 is just naming the binary `kubetest2-*` and calling into the shim `app.Main()` https://github.com/kubernetes/kops/blob/9dc910bdac92468793b4e4eff9b75524044291bd/tests/e2e/kubetest2-kops/main.go#L26

**Comment by chrislovecnm** [comment]
Closing this, as we are doing out of tree

**Comment by amwat** [comment]
Really happy to see this :) 
definitely reach out if you run into any core feature requests that would be helpful for all deployers.
