### ISSUE TITLE
Error installing kubetest2

### ISSUE THREAD

**Issue by SameerMahajan-GSLab** [kubernetes-sigs/kubetest2#137]
From the instructions to install kubetest2 I am running:

GO111MODULE=on go get sigs.k8s.io/kubetest2/...@latest

when I get error

go get: can't request version "latest" of pattern "sigs.k8s.io/kubetest2/..." that includes the main module (sigs.k8s.io/kubetest2)

what am I missing?

**Comment by amwat** [comment]
Most likely you might be running this from the main working directory of a checkout of kubetest2 repo itself?

can you try running it from outside a go module project working directory? https://github.com/kubernetes-sigs/kubetest2/issues/118#issuecomment-806157770

**Comment by SameerMahajan-GSLab** [comment]
Thanks @amwat that helped. How do you run k8s e2e tests with kubetest2? Pardon my questions as I am a newbie.

**Comment by amwat** [comment]
No worries!

There's some docs over at https://github.com/kubernetes/community/blob/2bf70285c638872f0e1e8650ab6ce1df6a4ba25c/contributors/devel/sig-testing/e2e-tests-kubetest2.md#testing-against-an-existing-cluster

the user documentation in this repo is really lacking! (https://github.com/kubernetes-sigs/kubetest2/issues/134)

/close 

since the original issue seems to be resolved
