### ISSUE TITLE
Unsafe concurrent use of bytes.Buffer

### ISSUE THREAD

**Issue by liggitt** [kubernetes-sigs/kubetest2#210]
https://github.com/kubernetes-sigs/kubetest2/blob/master/pkg/process/junitexec.go#L59-L61 uses the same bytes.Buffer in two output streams, which means it can be written to concurrently. That is not threadsafe.

This panics randomly with changes made to bytes.Buffer growing in go1.19.

The code should be changes to make use of the buffer threadsafe or use two separate buffers

**Comment by BenTheElder** [comment]
For the next time we run into something like this: It's actually [slightly more complex than that in the general case]( https://github.com/kubernetes-sigs/kind/blob/ad1e16c767ebc8129785b9f440baa6b28438db05/pkg/exec/local.go#L83) but not here since we always set os.Stdout and os.Stderr

This should use a mutex wrapped buffer.

**Comment by BenTheElder** [comment]
Actually, I will just do this before PRing myself to emeritus, since this is such a trivial but important fix ...
